import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const root = path.resolve("outputs/say-more-1000-online-game");
const sourceRows = JSON.parse(
  await fs.readFile("outputs/say-more-500-online-game/say_more_500_card_library.json", "utf8"),
).rows;

const colName = (index) => {
  let name = "";
  let n = index;
  while (n > 0) {
    const rem = (n - 1) % 26;
    name = String.fromCharCode(65 + rem) + name;
    n = Math.floor((n - 1) / 26);
  }
  return name;
};

const a1 = (row, col, rowCount = 1, colCount = 1) => {
  const start = `${colName(col)}${row}`;
  const end = `${colName(col + colCount - 1)}${row + rowCount - 1}`;
  return start === end ? start : `${start}:${end}`;
};

const depthFor = (index) => (index < 15 ? "Low" : index < 35 ? "Medium" : "High");

const makePack = (setName, prefix, treatment, prompts) =>
  prompts.map((prompt, index) => ({
    ID: `${prefix}-${String(index + 1).padStart(2, "0")}`,
    Set: setName,
    Category: setName,
    "Card Type": "Question",
    Level: index < 17 ? "Level 1" : index < 34 ? "Level 2" : "Level 3",
    "Suggested Mode": setName,
    Depth: depthFor(index),
    Prompt: prompt,
    "Design Treatment": treatment,
    "Facilitator Note": depthFor(index) === "High" ? "Best after trust has warmed up; passing is always allowed." : "Suitable for early playtesting.",
    Rationale: `Expands the ${setName} play context.`,
  }));

const packs = [
  makePack("Strangers on Camera", "SOC", "Camera Black / Warm Cream", [
    "What is something people might not guess from looking at you?",
    "What part of your story would make a good opening scene?",
    "What is one question you wish interviewers asked more often?",
    "What do you hope people feel after hearing you speak?",
    "What is a small detail that says a lot about you?",
    "What is one belief you carry into every room?",
    "What does your voice sound like when you feel safe?",
    "What is one thing you want to be known for beyond your work?",
    "What is a place that shaped your way of seeing people?",
    "What is a moment you wish someone had recorded?",
    "What is a story you usually edit down too much?",
    "What is something you learned from someone much older than you?",
    "What is something you learned from someone much younger than you?",
    "What is one assumption people make about your background?",
    "What is one thing your background gave you that you treasure?",
    "When have you felt like an outsider in a room?",
    "When have you felt unexpectedly welcomed?",
    "What is a question that could help two very different people begin?",
    "What do you think people get wrong about loneliness?",
    "What do you think people get right about connection?",
    "What is one public moment when you felt seen?",
    "What is one public moment when you felt invisible?",
    "What is one thing you wish your younger self could hear you say?",
    "What is a turning point that still affects how you connect?",
    "What kind of difference are you no longer afraid of?",
    "What is one thing you want to understand about people unlike you?",
    "What is a memory that changed how you listen?",
    "What is a story you inherited but had to rewrite?",
    "What is something you believe because of where you come from?",
    "What is something you believe because you left where you came from?",
    "What part of your identity feels easiest to explain?",
    "What part of your identity feels hardest to explain?",
    "What is one question that makes you feel respected?",
    "What is one question that makes you shut down?",
    "What does dignity mean to you in conversation?",
    "What is one truth you wish more people would sit with?",
    "What is one story you are tired of being asked to represent?",
    "What is one story you are proud to represent?",
    "What do you protect when you are being watched?",
    "What becomes possible when the camera feels kind?",
    "What is one answer you are still growing into?",
    "What is one silence you would not want edited out?",
    "What does being understood across difference require?",
    "What is something you can offer this room that no one else can?",
    "What is one thing you hope survives the edit?",
    "What question would reveal the person behind the performance?",
    "What would make this conversation feel honest on camera?",
    "What do you want strangers to remember about your humanity?",
    "What bridge do you want your story to build?",
    "What should the final question of this interview be?",
  ]),
  makePack("Dinner Party", "DIN", "Wine / Candlelight", [
    "What is the best thing you have eaten recently?",
    "What is a dinner table rule you secretly believe in?",
    "What is your ideal seat at a dinner party?",
    "What topic always wakes up a room?",
    "What is a story you can tell in under one minute?",
    "What is one thing you would bring to a shared table?",
    "What is a meal that feels like home?",
    "What is a host habit you always notice?",
    "What is a guest habit you appreciate?",
    "What is a conversation you love overhearing?",
    "What is a harmless debate you could start right now?",
    "What is a food opinion you stand by?",
    "What is the best kind of toast?",
    "What is a small luxury that improves any gathering?",
    "What makes a room feel generous?",
    "What is a question that works with almost anyone?",
    "What is a story your friends always ask you to tell?",
    "What is something you recently learned at a table?",
    "What kind of music belongs in the background tonight?",
    "What is a party you still think about?",
    "What is a party you wish you could redo?",
    "What is one thing that makes people linger after dinner?",
    "What makes conversation feel effortless?",
    "What makes conversation feel like work?",
    "Who taught you how to host, directly or indirectly?",
    "What is a tradition you would start with friends?",
    "What is one question that could make this table kinder?",
    "What is one thing people should stop apologizing for at dinner?",
    "What is a moment when strangers became less strange?",
    "What is your favorite kind of shared silence?",
    "What is something you want more people to ask you about?",
    "What is something you are happy to explain badly?",
    "What is one way this table could surprise itself?",
    "What is a compliment someone here might need?",
    "What is one memory that tastes like a specific food?",
    "What did your childhood dinner table teach you?",
    "What did your childhood dinner table not teach you?",
    "What is a topic you avoid until you trust the room?",
    "What makes you feel included in a group conversation?",
    "What makes you disappear in a group conversation?",
    "What is one truth best said after dessert?",
    "What is one question you would ask if no one could judge it?",
    "What is a room you are still trying to belong in?",
    "What kind of people make you feel more alive?",
    "What is a gathering you wish existed?",
    "What should every good dinner party make room for?",
    "What would you want this table to remember about you?",
    "What should we talk about before everyone leaves?",
    "What is one thing you are taking from this table?",
    "What is the toast this room deserves?",
  ]),
  makePack("Best Friends", "BFF", "Sky Blue / Clay", [
    "What is a memory of us that still makes you laugh?",
    "What is a memory of us that still makes you emotional?",
    "What do you think we understood about each other quickly?",
    "What is one thing I do that feels very me?",
    "What is one thing you think I forget about myself?",
    "What kind of friend am I when I am at my best?",
    "What kind of friend am I when I am overwhelmed?",
    "What should we celebrate about this friendship?",
    "What is a tradition we should protect?",
    "What is a tradition we should start?",
    "What story from our friendship deserves a title?",
    "What era of our friendship do you miss?",
    "What era of our friendship are you glad we survived?",
    "What is one thing we can talk about without explaining too much?",
    "What is one thing we still do not know about each other?",
    "What is a way I have changed that you noticed?",
    "What is a way you have changed that you hope I noticed?",
    "What do you trust me with?",
    "What do you wish you trusted more people with?",
    "What is a boundary that keeps our friendship healthy?",
    "What is a small check-in that would help us stay close?",
    "What does loyalty look like between us now?",
    "What is a friendship habit we have outgrown?",
    "What is a friendship habit we should bring back?",
    "What is something I helped you through without knowing?",
    "What is something you helped me through without knowing?",
    "What do you think people misunderstand about our friendship?",
    "What is a moment when you felt proud of me?",
    "What is a moment when you felt protective of me?",
    "What is something you wish I asked you more often?",
    "What is something you want me to stop minimizing?",
    "What is a dream of mine you still remember?",
    "What is a dream of yours you want me to remember?",
    "What is a version of me you miss?",
    "What is a version of me you are glad I became?",
    "What has distance taught us?",
    "What has closeness taught us?",
    "What is an apology our friendship taught you how to make?",
    "What is a repair our friendship still needs?",
    "What is one thing we should forgive our younger selves for?",
    "What is something you want us to be honest about now?",
    "What is a hard thing you would trust me to hear?",
    "What is a kind thing you have not said out loud yet?",
    "What do you hope our friendship looks like in ten years?",
    "What do you hope never changes between us?",
    "What do you hope keeps changing between us?",
    "What is one promise we should make to this friendship?",
    "What would make us feel closer this season?",
    "What should I thank you for more specifically?",
    "What should we never stop laughing about?",
  ]),
  makePack("Siblings", "SIB", "Sage / Family Clay", [
    "What is a childhood memory only we would understand?",
    "What is a family story we remember differently?",
    "What did we survive together without naming it?",
    "What did our home teach us about love?",
    "What did our home teach us about conflict?",
    "What is one thing you think I got blamed for unfairly?",
    "What is one thing you think you got blamed for unfairly?",
    "What role did I play growing up?",
    "What role did you play growing up?",
    "What family role are you trying to outgrow?",
    "What family role are you proud to carry?",
    "What is something I protected you from, knowingly or not?",
    "What is something you protected me from, knowingly or not?",
    "What is a small object that reminds you of our childhood?",
    "What is a sound that takes you back instantly?",
    "What is a meal that tastes like where we come from?",
    "What did you envy about me growing up?",
    "What did you admire about me growing up?",
    "What do you think I envied about you?",
    "What do you think I admired about you?",
    "What is something we never got to say as kids?",
    "What is something we can finally laugh about?",
    "What is something we still need to be gentle around?",
    "What do you think our parents understood about us?",
    "What do you think our parents missed about us?",
    "What did you need more of from me?",
    "What did I need more of from you?",
    "What is one way we became different for good reasons?",
    "What is one way we are more alike than we admit?",
    "What is a family pattern you want to end?",
    "What is a family strength you want to keep?",
    "What does being siblings mean now that we are older?",
    "What do you wish I knew about your version of childhood?",
    "What do you want to know about my version of childhood?",
    "What is a memory that still feels tender?",
    "What is a memory that still feels joyful?",
    "What apology would help us breathe easier?",
    "What thank you is overdue between us?",
    "What boundary would help us be closer?",
    "What conversation have we delayed too long?",
    "What do you hope I understand about who you are now?",
    "What do you want to understand about who I am now?",
    "What should we stop making jokes about?",
    "What should we never stop making jokes about?",
    "What is one thing we can give each other that our family could not?",
    "What would repair look like between us?",
    "What would closeness look like between us?",
    "What do you hope future family members learn from us?",
    "What should we carry forward together?",
    "What should we leave behind together?",
  ]),
  makePack("Parent & Child", "PAC", "Warm Cream / Deep Green", [
    "What is a memory of us you hope I keep?",
    "What is a memory of us you wish we talked about more?",
    "What did you need from me that was hard to ask for?",
    "What did I need from you that was hard to give?",
    "What do you think I understood too late?",
    "What do you think you understood too late?",
    "What is something you are proud of in how I grew?",
    "What is something you are proud of in how you grew?",
    "What did our relationship teach you about love?",
    "What did our relationship teach you about patience?",
    "What is a tradition you hope continues?",
    "What is a tradition you would like to change?",
    "What is one story from before I knew you well?",
    "What is one story from before you knew me well?",
    "What is something you wish I asked about your life?",
    "What is something you wish I asked about your childhood?",
    "What did you worry about that I never knew?",
    "What did I worry about that you never knew?",
    "What did protection look like to you?",
    "What did freedom look like to you?",
    "What is one way we misunderstood each other's intentions?",
    "What is one way we loved each other imperfectly?",
    "What did you have to learn without a map?",
    "What did I have to learn without a map?",
    "What is one thing you hope I forgive?",
    "What is one thing you are learning to forgive?",
    "What is one thank you that is overdue?",
    "What is one apology that would still matter?",
    "What does respect mean between us now?",
    "What does closeness mean between us now?",
    "What boundary would make our relationship healthier?",
    "What question feels safer to ask now than before?",
    "What do you wish I knew about your sacrifices?",
    "What do you wish I knew about your dreams?",
    "What do you wish I knew about your loneliness?",
    "What is something we should stop avoiding?",
    "What is something we should stop assuming?",
    "What is a way I still need you?",
    "What is a way you still need me?",
    "What does being proud of someone feel like to you?",
    "What does being disappointed mean without losing love?",
    "What do you want our next chapter to include?",
    "What should our relationship make more room for?",
    "What should our relationship release?",
    "What would healing look like in small steps?",
    "What would trust look like in small steps?",
    "What is one thing you want remembered clearly?",
    "What is one thing you want understood gently?",
    "What should we say while we still can?",
    "What kind of relationship are we still allowed to build?",
  ]),
  makePack("Teens & Young Adults", "TYA", "Electric Teal / Cream", [
    "What is one pressure people your age are tired of explaining?",
    "What makes you feel like yourself online?",
    "What makes you feel unlike yourself online?",
    "What is a place where you feel you belong?",
    "What is a place where you feel you perform?",
    "What is one thing adults misunderstand about your generation?",
    "What is one thing your generation misunderstands about adults?",
    "What is something you are excited to become?",
    "What is something you are afraid to become?",
    "What does confidence look like on you?",
    "What does insecurity make you hide?",
    "What is one friendship question you are still figuring out?",
    "What makes a group chat feel safe?",
    "What makes a group chat feel stressful?",
    "What is one dream you have not said out loud much?",
    "What is one expectation you wish would loosen?",
    "What is one label that does not fit you anymore?",
    "What is one label you are growing into?",
    "What makes school, work, or life feel too loud?",
    "What helps you come back to yourself?",
    "What is one thing you want older people to ask you?",
    "What is one thing you want younger people to know?",
    "What is a compliment that feels real?",
    "What is criticism that actually helps?",
    "What does success currently mean to you?",
    "What does success no longer mean to you?",
    "What are you trying not to compare?",
    "What are you secretly proud of?",
    "What do you wish your friends noticed?",
    "What do you wish your family noticed?",
    "What is one way loneliness shows up at your age?",
    "What is one way connection shows up at your age?",
    "What makes you feel chosen by friends?",
    "What makes you feel replaceable?",
    "What do you do when you feel left out?",
    "What would make asking for help easier?",
    "What is one thing you wish you could pause?",
    "What is one thing you wish would start already?",
    "What does growing up feel like this week?",
    "What are you learning about your boundaries?",
    "What are you learning about your voice?",
    "What is one opinion you are not ready to defend yet?",
    "What is one truth you are ready to defend?",
    "What would make the future feel less lonely?",
    "What would make the future feel more yours?",
    "What is one thing you want to be remembered for now?",
    "What is one thing you hope changes before you are older?",
    "What is one thing you hope never changes about you?",
    "What kind of adult do you hope to become?",
    "What should people know about becoming yourself?",
  ]),
  makePack("Life Transitions", "LIF", "Terracotta / Mist", [
    "What chapter of life are you in right now?",
    "What chapter are you leaving?",
    "What chapter are you afraid to enter?",
    "What is one thing you are grieving that looks like growth?",
    "What is one thing you are gaining that still feels strange?",
    "What did change teach you about control?",
    "What did change teach you about trust?",
    "What did you have to leave behind to move forward?",
    "What are you carrying that still helps you?",
    "What are you carrying that has become heavy?",
    "What is one goodbye you did not get to say properly?",
    "What is one hello you are still practicing?",
    "What does starting over feel like in your body?",
    "What does uncertainty make you reach for?",
    "What does uncertainty make you avoid?",
    "Who helped you through a transition?",
    "Who did you become in a transition?",
    "What is a place that belongs to your old life?",
    "What is a place that belongs to your new life?",
    "What is something you miss more than expected?",
    "What is something you do not miss at all?",
    "What is one dream that changed shape?",
    "What is one dream that stayed?",
    "What did you learn about loneliness during change?",
    "What did you learn about connection during change?",
    "What is one routine that steadies you?",
    "What is one routine you need to rebuild?",
    "What is something you are allowed to outgrow?",
    "What is something you are allowed to keep?",
    "What is one identity you are releasing?",
    "What is one identity you are becoming?",
    "What is one fear that got louder during this transition?",
    "What is one courage that got louder during this transition?",
    "What are you still waiting to understand?",
    "What are you finally able to name?",
    "What is one thing you wish people knew about this season?",
    "What kind of support would actually help right now?",
    "What kind of advice does not help right now?",
    "What is one thing you want to forgive yourself for?",
    "What is one thing you want to thank yourself for?",
    "What would make this transition feel less lonely?",
    "What would make this transition feel more meaningful?",
    "What would your past self not believe about now?",
    "What would your future self want you to protect?",
    "What is one small sign you are healing?",
    "What is one small sign you are ready?",
    "What is one question this season keeps asking you?",
    "What answer are you slowly living into?",
    "What should this chapter teach you?",
    "What should this chapter not take from you?",
  ]),
  makePack("Self-Discovery", "SEL", "Ivory / Ink", [
    "What part of yourself are you meeting lately?",
    "What part of yourself are you avoiding lately?",
    "What is a value you want to live more visibly?",
    "What is a value you inherited but are questioning?",
    "What makes you feel most honest with yourself?",
    "What makes you perform even when no one asks?",
    "What is one truth your body knows before your mind does?",
    "What is one feeling you intellectualize too quickly?",
    "What is one need you minimize?",
    "What is one desire you keep negotiating down?",
    "What is a pattern you can finally recognize?",
    "What is a pattern you are ready to interrupt?",
    "What is something you are learning not to explain?",
    "What is something you are learning to say plainly?",
    "What does peace look like when it is not perfection?",
    "What does confidence look like when it is quiet?",
    "What do you do to feel in control?",
    "What do you do when control stops working?",
    "What is one version of yourself you miss?",
    "What is one version of yourself you are proud to have outgrown?",
    "What is one thing you are still waiting for permission to be?",
    "What would you do if you trusted your own timing?",
    "What would you stop doing if you trusted your own worth?",
    "What is a boundary that would honor your future self?",
    "What is a choice that would honor your younger self?",
    "What is one question you are scared to answer honestly?",
    "What is one question you are ready to answer honestly?",
    "What kind of love are you learning to give yourself?",
    "What kind of love are you learning to receive?",
    "What does your inner critic sound like?",
    "What does your inner wisdom sound like?",
    "What is one thing you know but keep doubting?",
    "What is one thing you doubt but want to know?",
    "What do you want your life to make room for?",
    "What do you want your life to stop organizing around?",
    "What is one fear that has been trying to protect you?",
    "What is one joy that has been trying to return?",
    "What would be different if you believed you were enough?",
    "What would be different if you stopped rushing?",
    "What is one promise you have broken to yourself?",
    "What is one promise you want to keep now?",
    "What are you learning about your capacity?",
    "What are you learning about your limits?",
    "What are you learning about your voice?",
    "What are you learning about your silence?",
    "What is one truth you want to practice living?",
    "What is one mask you are tired of adjusting?",
    "What is one freedom you are not used to yet?",
    "What would self-trust ask you to do next?",
    "What would self-respect ask you to stop doing?",
  ]),
  makePack("After Dark", "AFT", "Midnight / Ember", [
    "What feels easier to admit at night?",
    "What thought visits you when everything is quiet?",
    "What is a truth you usually soften in daylight?",
    "What is a desire you are learning not to shame?",
    "What is a loneliness you rarely name?",
    "What is a comfort you reach for when no one is watching?",
    "What is a memory that still glows?",
    "What is a memory that still aches?",
    "What are you pretending not to want?",
    "What are you pretending not to know?",
    "What is something you miss with your whole body?",
    "What is something you crave that is not a thing?",
    "What kind of attention makes you feel alive?",
    "What kind of attention makes you feel unsafe?",
    "What do you want to be brave enough to say first?",
    "What do you want someone else to be brave enough to ask?",
    "What is a secret you can share without betraying yourself?",
    "What is a boundary that protects your tenderness?",
    "What is a risk you still think about?",
    "What is a choice you wonder about at night?",
    "What is one thing you would do if longing were not embarrassing?",
    "What is one thing you would stop doing if fear were quieter?",
    "What kind of closeness scares you?",
    "What kind of closeness steadies you?",
    "What is a goodbye that still echoes?",
    "What is a hello you wish had lasted longer?",
    "What do you want to feel before you fall asleep?",
    "What do you want to wake up no longer carrying?",
    "What is one apology you rehearse silently?",
    "What is one confession you are not ready to make?",
    "What does honesty cost you?",
    "What does hiding cost you?",
    "What is one ache that taught you something?",
    "What is one pleasure that taught you something?",
    "What is a version of you that only appears late at night?",
    "What is a question you would answer only in the dark?",
    "What is one thing you wish someone noticed without being told?",
    "What is one thing you wish someone asked before touching emotionally?",
    "What is one thing you want to be chosen for?",
    "What is one thing you want to stop auditioning for?",
    "What is intimacy teaching you lately?",
    "What is solitude teaching you lately?",
    "What is one fantasy that is really about being understood?",
    "What is one fear that is really about being left?",
    "What truth would change the room if you said it?",
    "What silence would change the room if you honored it?",
    "What do you want to keep sacred?",
    "What do you want to release before morning?",
    "What should this night make possible?",
    "What should stay between us after this card?",
  ]),
  makePack("Creative Minds", "CRE", "Ink / Signal Yellow", [
    "What idea will not leave you alone?",
    "What are you making before you know how to explain it?",
    "What does your taste say about you?",
    "What kind of work makes you lose track of time?",
    "What kind of work makes you feel invisible?",
    "What is a creative risk you respect?",
    "What is a creative risk you are avoiding?",
    "What is something you made that taught you who you are?",
    "What is something you abandoned that still taught you something?",
    "What does failure make you believe too quickly?",
    "What does failure make possible later?",
    "What is a compliment about your work that stayed with you?",
    "What is criticism that actually made you better?",
    "What is criticism that only made you smaller?",
    "What does discipline look like without self-punishment?",
    "What does inspiration look like when it is practical?",
    "What are you tired of pretending is effortless?",
    "What are you secretly working very hard for?",
    "What audience do you imagine too often?",
    "What audience do you need to remember more?",
    "What does success mean for this season of your work?",
    "What does success no longer mean for your work?",
    "What is one creative rule you want to break?",
    "What is one creative rule you still believe in?",
    "What is a constraint that helps you?",
    "What is a constraint that hurts you?",
    "What do you wish collaborators understood about your process?",
    "What do you wish you understood about collaboration?",
    "What is one idea you are scared is too honest?",
    "What is one idea you are scared is too strange?",
    "What kind of beauty are you drawn to lately?",
    "What kind of truth are you drawn to lately?",
    "What part of your work feels most alive?",
    "What part of your work feels most protected?",
    "What is something you would make if money were quieter?",
    "What is something you would make if approval were quieter?",
    "What does your younger creative self still need?",
    "What does your future creative self need you to practice?",
    "What is a project that changed your standards?",
    "What is a project that changed your courage?",
    "What is a dream you are afraid to make specific?",
    "What is a dream you are ready to make specific?",
    "What does your work help you understand about loneliness?",
    "What does your work help you understand about connection?",
    "What are you trying to say in more than one way?",
    "What are you done hiding behind style?",
    "What should your next experiment teach you?",
    "What should your next experiment not need to prove?",
    "What do you want your work to make room for?",
    "What would you make if you trusted your voice fully?",
  ]),
];

const normalize = (row) => ({
  ID: row.ID,
  Set: row.Set,
  Category: row.Category,
  "Card Type": row["Card Type"],
  Level: row.Level,
  "Suggested Mode": row["Suggested Mode"],
  Depth: row.Depth,
  Prompt: row.Prompt,
  "Design Treatment": row["Design Treatment"],
  "Facilitator Note": row["Facilitator Note"],
  Rationale: row.Rationale,
});

const rows = [...sourceRows.map(normalize), ...packs.flat()];
await fs.mkdir(root, { recursive: true });

const headers = Object.keys(rows[0]);
const csvEscape = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
const csv = [headers.map(csvEscape).join(","), ...rows.map((row) => headers.map((h) => csvEscape(row[h])).join(","))].join("\n");
await fs.writeFile(path.join(root, "say_more_1000_card_library.csv"), csv, "utf8");
await fs.writeFile(path.join(root, "say_more_1000_card_library.json"), JSON.stringify({ rows }, null, 2), "utf8");

const countsBySet = rows.reduce((acc, row) => {
  acc[row.Set] = (acc[row.Set] ?? 0) + 1;
  return acc;
}, {});
const countsByCategory = rows.reduce((acc, row) => {
  acc[row.Category] = (acc[row.Category] ?? 0) + 1;
  return acc;
}, {});

const workbook = Workbook.create();
const overview = workbook.worksheets.add("Overview");
overview.getRange("A1:D7").values = [
  ["Say More 1000-Card Online Game Library", "", "", ""],
  ["Total Cards", rows.length, "", ""],
  ["Previous Library", 500, "Base plus dating and friendship packs", ""],
  ["New Topic Packs", 500, "10 packs x 50 cards", ""],
  ["Product Direction", "Full online card-game library", "", ""],
  ["Safety Principle", "Pass, pause, or choose a gentler card at any time.", "", ""],
  ["Use", "Browser game, playtesting, print/source card production", "", ""],
];

const setSheet = workbook.worksheets.add("Counts by Set");
setSheet.getRange("A1:B1").values = [["Set", "Count"]];
setSheet.getRange(a1(2, 1, Object.keys(countsBySet).length, 2)).values = Object.entries(countsBySet);

const categorySheet = workbook.worksheets.add("Counts by Category");
categorySheet.getRange("A1:B1").values = [["Category", "Count"]];
categorySheet.getRange(a1(2, 1, Object.keys(countsByCategory).length, 2)).values = Object.entries(countsByCategory);

const cardSheet = workbook.worksheets.add("Cards");
cardSheet.getRange(a1(1, 1, 1, headers.length)).values = [headers];
cardSheet.getRange(a1(2, 1, rows.length, headers.length)).values = rows.map((row) => headers.map((h) => row[h]));

const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(path.join(root, "say_more_1000_card_library.xlsx"));

console.log(JSON.stringify({ cards: rows.length, countsBySet, root }, null, 2));
